default:
  image: php:8.4-fpm-alpine
  tags:
    - galaxy-docker-shared
  cache:
    - key: composer-cache
      paths:
        - .composer-cache/
  before_script:
    - composer config -g cache-dir "$(pwd)/.composer-cache"

code-analysis:
  stage: test
  script:
    - composer install --no-interaction
    - composer audit
    - vendor/bin/php-cs-fixer check --diff
    - vendor/bin/phpstan analyse
